### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/datapackage-r#1]
# Description

This issue documents the initial steps to get started with a new Frictionless Data implementation.

# Tasks

- [ ] Travis configuration
- [ ] Coveralls configuration
- [ ] Basic setup of README with badges
- [ ] Basic setup of license
- [ ] Review the whole family of [specifications](http://specs.frictionlessdata.io)
- [ ] Review the [implementation notes](http://specs.frictionlessdata.io/implementation/)
- [ ] Review either the Python ([Data Package](https://github.com/frictionlessdata/datapackage-py) [Table Schema](https://github.com/frictionlessdata/tableschema-py)) or JavaScript ([Data Package](https://github.com/frictionlessdata/datapackage-js) [Table Schema](https://github.com/frictionlessdata/tableschema-js)) reference implementations (whichever language you feel most comfortable reading)
  - [ ] Note that we have high nineties test coverage on these libraries. Similar test coverage is expected here
- [ ] Review the [stack reference](https://github.com/frictionlessdata/stack#frictionless-data-stack)
- [ ] Review the blog post that announces [v1 of the specifications](https://hackmd.io/KwUzE5wIwRgWgGYENzDgFmAgzHKA2fJOABmHwGMATEmK8GIoA===)
- [ ] Review the test packages that can be used to [test your work](https://github.com/frictionlessdata/testsuite-py/tree/master/datasets) (in addition to the normal and expected unit tests)
- [ ] Review the [OKFN Coding Standards](https://github.com/okfn/coding-standards)
  - Parts of the coding standard are language specific, and parts are workflow specific. The workflow points are important for you. If you want to contribute language-related standards to our docs for your language, we welcome it!
- [ ] Write a set of high-level issues for each library, on the respective issue tracker, that outline the work plan
  - Note the structure of this issue: A narrative description and a specific list of tasks. Follow a similar pattern
  -  The sequence of work is important: start with the Table Schema library first, as the Data Package library has a direct dependency on it
- [ ] Note the communication protocol for this work: All communication around the implementation must be in public. We want our work dynamic here to serve as an example for other implementors, and to share as much information as possible. There are two channels of communication:
  - GitHub Issues on tableschema-{LANG} and datapackage-{LANG}
  - Gitter chat at https://gitter.im/frictionlessdata/chat where all the core team at OKI are available for assistance
- [ ] Note the staff from OKI who are here to support you:
  - [Jo Barratt](https://github.com/jobarratt) - Project Manager for Frictionless Data
  - [Evgeny Karev](https://github.com/roll) - Tech Lead for core Frictionless Data libraries
  - [Serah Rono](https://github.com/callmealien) - Developer Advocate at Open Knowledge International, Dissemination Lead for the Tool Fund
  - [Dan Fowler](https://github.com/danfowler) - Developer Advocate at Open Knowledge International, Pilot Lead for Frictionless Data, OKI Labs Lead
  - [Adam Kariv](https://github.com/akariv) - Engineering Lead at Open Knowledge International, Tech Lead on OpenSpending
  - [Paul Walsh](https://github.com/pwalsh) - Chief Product Officer at Open Knowledge International
- Any communication around the grant agreement should be directly done by email with Jo Barratt, Frictionless Data Project Manager

**Comment by roll** [comment]
Closing. Please use individual issues for everything that is left
