### ISSUE TITLE
Finishing up

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/datapackage-r#2]
# Description

This issue describes the set of tasks to complete in order to finish up work on the library.

# Tasks

- [ ] Touch base with the @jobarratt and @pwalsh to notify that you consider the work complete
- [ ] Provide a short description / link to code for how each action is implemented, with a link to unit tests that prove each action
- [ ] Tag your candidate code as v0.1
- [ ] Setup travis to auto deploy tagged versions to the package management solution for your language
- [ ] Ensure that the OKI account on the package management platform is an administrator/maintainer of the package, along with yourself
- [ ] Receive code review from @pwalsh and address any remaining issues
- [ ] Publish final version

**Comment by roll** [comment]
Closing. Please use individual issues for everything that is left
